remote_theme: pages-themes/minimal
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
title: ğŸ“š BibliothÃ¨que NumÃ©rique
show_downloads: true
description: Gestion complÃ¨te d'une bibliothÃ¨que numÃ©rique avec Python et interface terminal interactive.